root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ."
entrypoint = ".\\tmp\\main.exe"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", ".git"]
exclude_file = []
exclude_regex = ["_test\\.go"]
include_dir = []
follow_symlink = false
poll = false
delay = 200
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
